코드리뷰요청
Altu-Bitu/Altu-Bitu_seoyeon pull request #1
Opened 2021-09-06 13:45 UTC by flowersayo

@HyunJiLim0406  

1. 구조체를 정렬할때 sort 함수의 인자인 cmp함수를 구현할때 인자로 & 형식을 전달하던데 '&'가 의미하는 바가 c에서의 ' * '(포인터)와 비슷한 개념인가요? 그리고 이때 const 형식을 활용하는 이유가 뭔지 알 수 있을까요 ...!!!?

2.
+ 별찍기 문제빼고 다 풀었는데 그건 도저히 엄두가 안나네요 ,, ㅠㅠㅠ😂
제가 아직 유형에 안익숙해져서 그런걸까요 ..?! 
제가 생각나는 알고리즘은 다 비효율적(?)이고 지저분할거같아서 아직 시도를 안해봤어요 하하,, 
어떤식으로 구현하면 좋을지에 관해서 힌트 부탁드려도 될까요?! (ex. 3중포문을 써라 등)
감사합니다 !!! 😊

2021-09-06 15:25 UTC, HyunJiLim0406 requested changes
p1
답변을 드리다보니 시간이 너무 늦어졌네요ㅠ 이 알림으로 깨지 않으셔야 할텐데요
제가 튜터링에서 언급하지 않은 내용까지 알아보시다니...정말 감동이에요
코드도 좋고 주석도 꼼꼼하게 달아주셔서 리뷰하기 좋았네요!!
제가 생각지도 못했던 방법도 있어서 굉장히 흥미로웠습니다

근데 왜 p1이냐면...1946번에 적어놨어요!
시간복잡도 관련한 코멘트도 한 번 고민해주세요.

이제 질문 답변드릴게요!

1. 너무 좋은 질문이에요! 혹시 가능하다면 위 질문과 지금 드릴 답변을 질문 채널에 공유해도 될까요?
&는 음...포인터랑 비슷하긴 비슷해요..! &는 변수의 주소를 넘기겠다는 의미예요
 ```cpp
void func(int a){
	a = 3;
}

int main(){
	int a = 1;
	func(a);
	cout<<a;
}
```
이 코드의 실행 결과가 어떻게 될까요? 뭔가 3을 출력할 것 같지만 1을 출력해요!
왜냐면 func에 넘긴 a는 진짜 a가 아니라 a의 복사본이거든요! a의 복사본이 3이 된거라
당연히 원본 a는 여전히 1인거예요

cmp 함수에서 비교되는 인자들은 당연히 복사본이 아니라 원본이어야 하죠?
그래서 '&'를 사용해서 넘기는거예요.
func 함수에서 인자를 int &a로 바꿔보세요! 아마 3이 출력될거예요.

참고로 &를 통해서 넘기는게 없이 넘기는 것보다 실행시간도 빠르답니다! 복사할 필요가 없으니까요

핳..그럼 이렇게 '&'를 쓰는 이유는 설명했고, const는 왜 붙을까요?
const는 상수라는 뜻이잖아요. cmp 함수는 두 인자를 비교하는게 목적이에요.
근데 만약 어떤...나쁜 사람이 아니면 실수로 cmp 함수에서 인자를 수정한다면 어떻게 될까요?
그런 일이 일어나지 않도록 const를 붙여서 상수화 하는겁니다! 절대로 수정할 수 없고 읽기만 가능하도록 만드는거예요

답변이 됐을까요? 좋은 질문 주셔서 감사합니다!

2. 유형에 익숙하지 않으셔서 그런 것 같아요. 지금 작성해주신 코드들 보면 유형만 익히시면 빠르게 성장하실 것 같네요!
다른 크기의 같은 별이 반복돼서 나타나네요...! 저희가 이번에 merge sort 구현할 때 계속해서 배열을 쪼개기 위해 어떤 함수를 사용했나요? 한 번 재귀함수로 구현해볼까요?

아직 -ing인거 보니까 별찍기를 정복하고 싶으신거겠죠..!
제 피드백 반영하시고, 별찍기 푸셨다면 다시 한 번 리뷰어로 저 호출해주세요
아 그리고 정확한 커밋메세지는 [정렬] 9월 6일 - ing가 되겠네요!

그리고 처음 과제 제출할때는 튜터를 따로 호출하는게 아니예요!
과제 제출하시면 먼저 확인할 수 있는 튜터님이 가셔서 리뷰를 남겨주실거예요
근데 이젠 제가 리뷰어로 들어왔으니 이 pr에서 일어나는 수정은 저에게 알려주시면 됩니다!

2021-09-06 15:25 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/1026.cpp
> +	//sort함수는 퀵정렬을 이용한다.
정확히는 퀵정렬의 단점을 보완한 인트로 정렬을 사용해요!
이건 언급하지 않았는데 대단하시네요!

2021-09-06 15:25 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/1026.cpp
> +	//sort(start,end,greater<int>()); //내림차순으로 정렬하는 방법 2
내림차순 정렬을 두가지 방법으로 시도하셨네요! 좋은 시도예요 👍

2021-09-06 15:25 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/11399.cpp
> +	}
코드는 너무 잘 작성해주셨는데요. 지금 코드의 시간 복잡도는 O(n^2)이에요.
이 코드는 O(n)까지 줄일 수 있는데 한 번 고민해보시겠어요?
지금 작성해주신 주석을 잘 살펴보면 답이 나올 것 같아요!

2021-09-06 15:25 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/11651.cpp
> +};
구조체 선언해서 잘 구현하셨어요!
pair container도 알아보시겠어요?

2021-09-06 15:25 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/1316.cpp
> +		n--;
여기는 while(n--)으로 합치면 혹시 모를 실수를 예방할 수 있어요!

2021-09-06 15:25 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/1316.cpp
> +			}
이것도 아주 잘 작성하신 코드인데요.
같은 문자에 대해 등장여부를 계속 체크하게 될 수도 있을 것 같아요.
지금 코드는 시간복잡도가 O(n^2)인데 이 문제도 O(n)까지 시간을 줄일 수 있어요!
특정 알파벳이 등장했는지 안했는지 '어딘가에' 체크해두면 좋지 않을까요?

그룹 단어 체크하는 부분을 함수화하면 check 변수가 필요 없어질 것 같네요!

2021-09-06 15:25 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/13458.cpp
> +
맞아요!

2021-09-06 15:25 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/13458.cpp
> +
이 코드 벡터로 작성하면 어떻게 됐었나요?

2021-09-06 15:25 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/13458.cpp
> +				cnt+= (A[i]-1) / C + 1;
오 이렇게 처리하는 방법은 처음봐서 직접 돌려보고 왔어요.
전 생각도 못했던 방법인데 대단하시네요 👍

2021-09-06 15:25 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/1431.cpp
> +}
👍

2021-09-06 15:25 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/1431.cpp
> +	else //길이 같을때
if 조건문에 걸리면 무조건 true / false를 반환하죠?
그렇다면 else가 필요없지 않을까요~?

2021-09-06 15:25 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/1431.cpp
> +		else  //길이도 같고 sum도 같을때
여기도 마찬가지예요!

2021-09-06 15:25 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/1946.cpp
> +};
여기도 pair로 작성할 수 있어요!
이게 pair가 되면 필요없는 코드가 하나 더 생긴답니다!

2021-09-06 15:25 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/1946.cpp
> +
구조체와 변수명이 같은건 위험해요! 여기 꼭 고쳐주셔야 해요!!

2021-09-06 15:25 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/1946.cpp
> +		// -> 4등을 1,2,3등 각각과 비교하게 되면 O(N2)의 시간복잡도를 가지므로 시간초과. 따라서 max라는 변수를 선언하여 최고순위를 저장(1,2,3등중에서 가장 높은 순위)해두고 를 4등의 면접성적과 비교해준다.
👍 완벽하게 이해하셨습니다!

2021-09-06 15:25 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/1946.cpp
> +				//cout << grade[i].interview<< max_rank <<endl;
디버깅의 흔적일까요? 그렇다면 아주 훌륭한 위치예요!

2021-09-07 02:24 UTC, flowersayo commented on 9월 3일 - 정렬/11399.cpp
> +	}
엇 그렇네요 숫자들을 차례로 저장한것을 keep한다음에 sum에 저장하면 for문 한번으로도 처리할 수 있겠네요! 
이렇게 고쳤습니다 !
 
`int keep=0;

	for (int i = 0 ;i < n; i++) {

		keep += v[i]; 
		sum += keep; //+v[0] +v[0]+v[1]  +v[0]+v[1]+v[2] .... +v[0]+v[1]+v[2]... +v[n-1]


	}`

2021-09-07 02:25 UTC, flowersayo commented on 9월 3일 - 정렬/11399.cpp
> +	}
엇 그렇네요 숫자들을 차례로 저장한것을 keep한다음에 sum에 저장하면 for문 한번으로도 처리할 수 있겠네요!
이렇게 고쳤습니다 !

`int keep=0;

for (int i = 0 ;i < n; i++) {

	keep += v[i]; 
	sum += keep; //+v[0] +v[0]+v[1]  +v[0]+v[1]+v[2] .... +v[0]+v[1]+v[2]... +v[n-1]


}`

2021-09-07 02:28 UTC, flowersayo commented on 9월 3일 - 정렬/11399.cpp
> +	}
엇 그렇네요.. 숫자들을 차례로 저장한것을 keep한다음에 sum에 저장하면 for문 한번으로도 처리할 수 있겠네요!
이렇게 고쳤습니다 !

```c++ 
int keep=0;

for (int i = 0 ;i < n; i++) {

	keep += v[i]; 
	sum += keep; //+v[0] +v[0]+v[1]  +v[0]+v[1]+v[2] .... +v[0]+v[1]+v[2]... +v[n-1]


}```

2021-09-07 02:32 UTC, flowersayo commented on 9월 3일 - 정렬/11651.cpp
> +};
pair 컨테이너 개념은 알고있었는데 정작 활용을 못했었네요 핳ㅎ,, , 튜터님 말씀대로 2개의 값을 저장할일이 있을때에는 pair container로 구현하면 굳이 번거롭게 구조체를 생성하는 작업을 하지 않아도 되어서 코드도 간결해지고 사용도 더 편리해질거같아요!  감사합니다~

2021-09-07 05:08 UTC, flowersayo commented on 9월 3일 - 정렬/1026.cpp
> +	//sort함수는 퀵정렬을 이용한다.
사실 cmp함수의 동작원리가 궁금해서 찾아봤었어요!   '>' 를 쓰면 오름차순으로 정렬되고 '<' 를 쓰면 내림차순으로 정렬된다는건 용례를 봐서 알겠는데 cmp 함수가 true를 반환하면 무슨일이 생기길래 그렇게 되는지 모르겠었거든요 .. 현지님께서 튜터링시간에 뭔가 true를 반환하면 swap이 일어나고 false를 반환하면 swap이 일어나지 않는다 (?) 식으로 설명해주셨던거같은데 사실 그 말이 잘 이해가 안됐었거든요!  찾아보니 sort 함수가 퀵정렬기반이고 거기에서 일어나는 swap 을 의미하는건가? 하고 생각했는데 퀵정렬이 생각보다 어려워섷ㅎㅎ... 다음에 다시봐야지~ 하고 있었거든요 근데 퀵정렬이 아니라 인트로정렬이었다니 제가 나중에 한번 다시 찾아볼게요! 감사합니다 : )

2021-09-07 05:19 UTC, flowersayo commented on 9월 3일 - 정렬/1946.cpp
> +};
넵넵 지금 코드 바꾸기에는 너무 바꿔야할 것들이 많아져서 😂 그 점 참고해서 다음번에 문제 풀때에는 pair container 활용해보도록 하겠습니다!

2021-09-07 07:39 UTC, flowersayo commented on 9월 3일 - 정렬/1316.cpp
> +			}
오오옹 코멘트 듣자마자 bool배열? 이 딱 떠올라서 이부분도 수정했습니다! 피드백 감사합니다~ 

``` c++
bool isGroup(string str) { //그룹단어인지 확인하는 함수

	bool alphabet[26] = { false };// 특정알파벳이 등장했는지 안했는지 저장

	for (int i = 0; i < str.length(); i++) {

		
		

		if (i && str[i] != str[i - 1] && alphabet[str[i] - 'a']) //전문자와 같지않은데 알파벳이 나온적 있다면
		{
				
			return false; //그룹단어가 아니다.	
		}

		alphabet[str[i] - 'a'] = true; //나온 알파벳 저장.

	}
	
	return true;
}

2021-09-07 07:41 UTC, flowersayo commented on 9월 3일 - 정렬/13458.cpp
> +				cnt+= (A[i]-1) / C + 1;
한줄로 공식화할수있는 방법이 없을까 생각하다가 얼떨결에 때려맞춰진거같아요 하하ㅋㅋㅋ 감사합니다 !!

2021-09-07 08:47 UTC, flowersayo commented
제가 드린 답변 공유해주시는거 당연 가능합니다!!   앗 그리고 감동인건 오히려 튜티쪽인거같아요,,😂 이렇게 세세하고 정성스럽게 코드 리뷰 받아볼 기회가 살면서 저에게 올까하는 의문 ... (?) 처음에 실력이 딸리는거같아서  알튜비튜 신청할지 말지 엄청 고민했었는데 신청하길 넘 잘한거같아요,,ㅠㅠ!   사람수가 엄청 많아서 일일히 피드백해주기 정말 쉽지 않을텐데 튜터님들 최고에요 ,.,., 다시 한번 감사드립니다!!!

2021-09-07 08:53 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/1026.cpp
> +	//sort함수는 퀵정렬을 이용한다.
아하 그럼 이렇게 생각해보시는건 어떨까요?
저희 버블정렬 오름차순으로 구현할 때 arr[i-1]>arr[i] 였으면 swap을 했었죠? 그거랑 같아요!

인자로 넘어오는 i1, i2가 있다고 할게요.
그리고 cmp 함수한테 이렇게 물어보는거예요! 'i1이 i2보다 앞에 위치하는게 맞아?'
만약 true를 반환한다면 i1, i2라는 순서가 맞으니까 swap이 일어나지 않고
false라면 i1이 i2보다 뒤에 있어야 한다는 뜻이라 swap이 일어나는거예요!

2021-09-07 08:58 UTC, HyunJiLim0406 reviewed
p3
제가 드린 피드백을 완벽하게 이해하셨어요! 
별찍기 문제도 재귀함수 이용해서 아주 잘 푸셨네요~
merge 하셔도 좋아요. 8문제 다 풀었으니 쿠폰 기록하겠습니다~!

2021-09-07 08:58 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/10994.cpp
> +	}
벡터를 사용하면 이걸 한줄로 줄일 수 있어요! 이건 오늘 튜터링에서 다룰게요 ㅎㅎ

2021-09-07 10:52 UTC, merged