[분할정복] 10월 11일 -ing
Altu-Bitu/Altu-Bitu_seoyeon pull request #10
Opened 2021-10-11 01:05 UTC by flowersayo

1244,16198,17829,2447풀었습니다!

다만 2447은 실행을 해보면 프로그램이 벙찌고,
 17829는 디버깅해보니까 size =2 까지 제대로 matrix도 만들어지고  중간 과정 모두 잘 연산되었는데 
 이상하게 마지막 기저조건 연산에서만 0이 출력되어 왜 그런지 궁금합니다 😢😢

2021-10-11 10:24 UTC, bsa0322 requested changes
p2. 17829와 2447을 제외하곤 잘 풀어주셨네요!! 관련 코멘트는 아래에 남겼어요. 수정 후, 저 다시 리뷰어로 호출해주세요~~!! 수고하셨습니다!!

2021-10-11 10:24 UTC, bsa0322 commented on 10월 5일- 분할정복/1244.cpp
> +	}
p2. 시작과, 얼마나 증가해줄지 잘 설정하면 n의 배수에 바로 접근할 수 있어요!

2021-10-11 10:24 UTC, bsa0322 commented on 10월 5일- 분할정복/1244.cpp
> +	int max_symmetric =(n-1 < n_switch-n? n-1: n_switch - n); //대칭일수있는 최대길이 구하기.
p3. 삼항연산자는 가독성 등의 이유로 피해주는 게 좋아요! 두 수 중 더 큰 수를 구하는 직관적인 함수가 있었죠!

2021-10-11 10:24 UTC, bsa0322 commented on 10월 5일- 분할정복/1244.cpp
> +		}
p3. 대칭 횟수를 미리 구해서 연산을 한 번에 처리해주신 거 좋아요!!! 
왼쪽 오른쪽 2개밖에 없으니 위에서 대칭일 때 바로 처리해도 좋을 것 같아요~!!

2021-10-11 10:24 UTC, bsa0322 commented on 10월 5일- 분할정복/16198.cpp
> +			 max_energy = sum; //에너지 최댓값 갱신
p3. 이 부분도 함수를 사용하면 한 줄로 줄일 수 있겠네요!

2021-10-11 10:24 UTC, bsa0322 commented on 10월 5일- 분할정복/17829.cpp
> +	}
p3. 두 번째로 큰 수를 찾는 부분을 직접 구현해주신 거 좋아요!! 
그래도 정렬을 활용하면 더 간단하게 구현할 수 있겠네요!!

\+ INT_MIN 상수 선언이 없네요! 기존에 지원해주는(?) 상수인건가요?

2021-10-11 10:24 UTC, bsa0322 commented on 10월 5일- 분할정복/17829.cpp
> +		return findSecondLargest(0, 0, matrix);
기저조건에서 0이 출력된다는 질문에 답변 드리겠습니다!

size == 2는 함수의 가장 마지막 호출이에요. 여기서 return을 하면 바로 main으로 가는 게 아니라, 현재 함수를 호출한 그 전 함수로 돌아가게되죠! 그런데 현재 divide함수는 함수 호출 후 리턴한 값을 다시 return하는 연산이 없어요. main으로 보내주려면 어떻게 해야 할까요?

2021-10-11 10:24 UTC, bsa0322 commented on 10월 5일- 분할정복/2447.cpp
> +	}
27번째 줄에 주목해주세요! 반복문 안의 인덱스 증가 변수 사용에 사소한 실수가 있네요 😉

더불어 이를 해결하시면, 반복문의 종료 조건 설정도 다시 해주셔야 해요! 그리고 continue하는 부분의 위치도 바꿔주어야 겠네요!

2021-10-12 05:36 UTC, flowersayo commented on 10월 5일- 분할정복/1244.cpp
> +	int max_symmetric =(n-1 < n_switch-n? n-1: n_switch - n); //대칭일수있는 최대길이 구하기.
```
int max_symmetric = min(n - 1, n_switch - n);
```
넵넵~!

2021-10-12 05:36 UTC, flowersayo commented on 10월 5일- 분할정복/1244.cpp
> +	}
..!!!! 그렇네요
```
void changeMultiple(int n, int n_switch, vector <int>&  swt) { //n의 배수번째 스위치를 바꿈
	for (int i = n; i <= n_switch; i += n) {

		swt[i] = !swt[i]; //swap
	}
}
```

2021-10-12 05:42 UTC, flowersayo commented on 10월 5일- 분할정복/1244.cpp
> +		}
의도하신바가 이게 맞는진 모르겠지만 고쳐보았습니다 핳ㅎ....ㅎㅎ
```
void changeSymmetric(int n, int n_switch, vector <int>& swt) { //n을 기준으로 대칭인곳의 스위치를 전부 바꿈.

	// 기준점 :3 일때 01 1 10 이면 cnt=2
	int max_symmetric = min(n - 1, n_switch - n);

		swt[n] = !swt[n];
		for (int i = 1; i <= max_symmetric; i++) {

			if (swt[n - i] == swt[n + i])
			{
				swt[n - i] = !swt[n - i]; //swap
				swt[n + i] = !swt[n + i];
			}

			else break;

		}

}
```

2021-10-12 05:48 UTC, flowersayo commented on 10월 5일- 분할정복/16198.cpp
> +			 max_energy = sum; //에너지 최댓값 갱신
👍👍
```
max_energy = max(sum, max_energy); //에너지 최댓값 갱신
```

2021-10-12 05:54 UTC, flowersayo commented on 10월 5일- 분할정복/17829.cpp
> +	}
네 그렇더라구요(?)
![20211012145351](https://user-images.githubusercontent.com/86418674/136899345-de80455b-c82c-4b16-bba0-eec7a585ca57.png)

2021-10-12 05:55 UTC, flowersayo commented on 10월 5일- 분할정복/17829.cpp
> +	}
이 방법을 말씀하신게 맞을까요?🧐
```
int findSecondLargest(int row, int col , vector <vector<int>> matrix) { //2x2공간에서 두번째로 큰 수를 반환해주는 함수
	
	vector<int> arr;
	int first =INT_MIN, second= INT_MIN;
	for (int i = row; i < row + 2; i++) {

		for (int j = col; j < col + 2; j++) {

			arr.push_back(matrix[i][j]);
		}	
	}

	sort(arr.begin(), arr.end()); 
	return  arr[1];//두번째로 큰 수 반환
}
```

2021-10-12 07:09 UTC, flowersayo commented on 10월 5일- 분할정복/17829.cpp
> +		return findSecondLargest(0, 0, matrix);
아하...!!!! 제가 기본적인걸 놓치고 있었네요 감사합니다!
그래서 수아님 조언 듣고 단순히 이부분만 이런식으로 고쳤더니 답은 맞게 출력되는데 시간초과가 뜨더라구요 😢 
제 생각엔 매 호출마다 배열을 만들어서 그런것 같은데 맞나요? 근데 배열을 만들지 않고도 다음 호출에 어떤 숫자가 남았는지 정보를 전달할 방법이 있을까요..? 

```if (size == 2)  //기저조건 
	{
		cout << findSecondLargest(0, 0, matrix);
		return;
	}
```

2021-10-12 08:26 UTC, flowersayo commented on 10월 5일- 분할정복/2447.cpp
> +	}
엇 그렇네요! cnt++이 먼저오고 size가 아니라 row+size, col+size가 되어야할것같아요. 
조금더 정확하게 쓰면 ` row+ subsize*2+1`,`col+ subsize *2+1`이겠네요..! 피드백 넘 감사합니다 ㅠㅠ 
```
for (int i = row; i < row + size; i+= subsize) {

		for (int j = col; j < col + size; j+= subsize) {

			cnt++;
			if (cnt == 5)//중간 구역은 아무것도 출력하지 않음
				continue;
			makeSqure(subsize, i, j);
			
		}

	}
```

2021-10-12 11:08 UTC, flowersayo commented on 10월 5일- 분할정복/17829.cpp
> +		return findSecondLargest(0, 0, matrix);
이부분은 제가 샘플 코드확인하고 아이디어를 얻어서(?) 더 깔끔한 방향으로 코드 수정했습니다!

2021-10-12 11:34 UTC, flowersayo commented
17281번 추가제출합니다~~

2021-10-12 11:39 UTC, bsa0322 commented on 10월 5일- 분할정복/17829.cpp
> +	}
오 짱신기해여..👍👍

2021-10-12 11:43 UTC, bsa0322 approved these changes
아ㅜㅠ 제가 확인이 너무 늦었네요 죄송합니다.. 
수정해주신 부분 모두 확인했는데 다 좋아요!!! 222-풀링 시간초과는 너무 아쉽네요..기존 서연님 코드가 왜 시간초과였는지 찾게되면 또 코멘트 남길께요! 우선 수정해주셔서 222-풀링까지 체크할께요!
추가제출은 다른 튜터님이 확인해주실거예요. 너무 수고하셨습니다!!

2021-10-13 01:14 UTC, Yuna9949 commented
추가제출 확인되셨어요~~ 머지해주세요

2021-10-13 08:34 UTC, merged