[최소신장트리] 12월 6일
Altu-Bitu/Altu-Bitu_seoyeon pull request #18
Opened 2021-12-05 22:56 UTC by flowersayo

1368,16202,1713,1774,21924 풀었습니다! 문제들이 진짜 해결전략이 참신해서  재밌었어요 ,,ㅎㅎㅎ헣

그런데 21924는 기본 MST 문제라고 생각했는데 똑같이 구현하니까 틀렸습니다 받더라구요 혹시 제가 뭔가 잘못생각하고 있는게 있을까요?

2021-12-06 11:47 UTC, HyunJiLim0406 requested changes
p3 (21924 제외)
수고하셨습니다! 힌트가 도움이 됐다니 다행이네요! 힌트가 풀이 방향을 정해주기도 해서 다른 방향으로 풀이를 생각하셨다가 힌트때문에 혼란스러워하실까 걱정이 되기도 했었거든요 🥺
저희가 지금까지 다뤘던 과제들을 다 푸실 수 있다면 코테에서 막히는 일은 없을거예요! (비트마스킹은 좀 해야해요 하핳)
이번에 진짜 생각도 못했던 좋은 코드들이 많아서 저도 배워가네요!
21924번 틀린 이유는 코멘트로 달아놓았으니 확인해주세요!
그럼 수정 후 리뷰어로 저 불러주세요!!

2021-12-06 11:47 UTC, HyunJiLim0406 commented on 11월 30일- 최소신장트리/1368.cpp
> +                if (!visited[i] && graph[node][i] < dist[i]) { //MST에 포함되지 않았고 더 짧은 간선을 통해 갈 수 있다면)
line 44의 역할을 이미 하고 있는 구문이 있네요!

2021-12-06 11:47 UTC, HyunJiLim0406 commented on 11월 30일- 최소신장트리/16202.cpp
> +        }
아하 어차피 첫번째로 들어가는 간선은 무조건 사이클이 아니니까 제외되는 간선은 0번 인덱스부터 하나하나 늘어나겠네요!
허헣...저희 샘플 코드를 수정하러 가야겠는걸요

그나저나 이 문제는 간선 재활용이 많아요. 크루스칼의 핵심은 간선이 정렬되어 있어야 한다는 것인데, 그럼 우선순위 큐가 없어도 되지 않을까요?

2021-12-06 11:47 UTC, HyunJiLim0406 commented on 11월 30일- 최소신장트리/1713.cpp
> +	else { //후보에 없는경우 새로 올림.
여기서 그냥 return을 하면 else가 필요없어지네요!

2021-12-06 11:47 UTC, HyunJiLim0406 commented on 11월 30일- 최소신장트리/1713.cpp
> +		}
여기도 프레임이 남는 경우를 먼저 고려해서 리턴해버리면 인덴테이션이 깊게 들어가지 않아요

2021-12-06 11:47 UTC, HyunJiLim0406 commented on 11월 30일- 최소신장트리/1713.cpp
> +					if (rtime[min] > rtime[i]) //추천 받은 시각이 더 이를때만
line 40은 line 38에 합치는게 좋아요!

2021-12-06 11:47 UTC, HyunJiLim0406 commented on 11월 30일- 최소신장트리/1713.cpp
> +int main() {
학생 번호 범위가 작다는걸 잘 파악하셨네요!

2021-12-06 11:47 UTC, HyunJiLim0406 commented on 11월 30일- 최소신장트리/1774.cpp
> +    }
오 간선 가중치를 0으로 저장할 생각은 못했는데 이 방법도 진짜 좋네요!

2021-12-06 11:47 UTC, HyunJiLim0406 commented on 11월 30일- 최소신장트리/21924.cpp
> +
변수명 스네이크로 수정해주세요!

2021-12-06 11:47 UTC, HyunJiLim0406 commented on 11월 30일- 최소신장트리/21924.cpp
> +int main() {
알고리즘을 풀다 보면 아 이거였네...하는 경우가 아주 많아요. 이것도 그 중 하나인데요. 일단 이거였네...들을 나열해볼게요
1. 입출력 향상 처리 안해서 시간초과
2. 자료형 범위 실수 (double, long long 등)
3. 자료구조 사용시 pop안해서 시간초과
4. 배열에 크기 할당 안해서 런타임 에러
5. 오타

당장 생각나는건 이것 뿐이네요! 이것만 기억하시면 아마 틀렸습니다 맞은 문제들 중 절반은 잡아낼거예요!

2021-12-07 05:43 UTC, flowersayo commented on 11월 30일- 최소신장트리/1368.cpp
> +                if (!visited[i] && graph[node][i] < dist[i]) { //MST에 포함되지 않았고 더 짧은 간선을 통해 갈 수 있다면)
..!!! 그렇네요 node가 이미 방문처리 되었을 것이니 i가 자기자신을 가리키게 된다면 `!visited[i]` 에서 걸러지겠네요

2021-12-07 05:48 UTC, flowersayo commented on 11월 30일- 최소신장트리/16202.cpp
> +        }
그렇네요 이 문제는 처음부터 간선이 정렬된 상태(오름차순) 으로 주어지니까 벡터에 한번 담고 그걸로 계속 재활용(?) 해서 써도 될 것 같아요! 그럼 매번 pq에 넣는것보다 시간복잡도가 훨씬 줄겠네요 👍

2021-12-07 05:58 UTC, flowersayo commented on 11월 30일- 최소신장트리/1713.cpp
> +					if (rtime[min] > rtime[i]) //추천 받은 시각이 더 이를때만
```
else if ((recommend[min] == recommend[i]) && (rtime[min] > rtime[i])) // 추천수가 같으면 추천 받은 시각이 더 이를때만
			min = i; //교체		
```

2021-12-07 06:01 UTC, flowersayo commented on 11월 30일- 최소신장트리/1713.cpp
> +		}
그렇네요...!!!! `return` 을 활용할 생각을 전혀 못했어요
```
void post(int id,int prame,int t) {
	

	if (recommend[id]) { // 1. 이미 후보로 올라와있는경우

		recommend[id]++; //추천수 증가
		return ;

	}

	//2. 후보에 없는경우 새로 올림.

	if(n <prame){ // 액자 프레임 여유분이 남은경우

			recommend[id] =1;
			rtime[id] = t; 
			n++;
			return;
	}

 //최대정원에 도달하면 가장적은추천수 가진후보 찾고 교체.

	int min = 0; 
	recommend[0] = 1001;
	rtime[min] = 1001;
	for (int i = 1; i <= 100; i++) {

		if (recommend[i]==0 ) //받은 추천이 없다면
			continue; 
	
		if (recommend[min] > recommend[i])  // 추천수가 더 적으면 
			min = i; //교체
			
		else if ((recommend[min] == recommend[i]) && (rtime[min] > rtime[i])) // 추천수가 같으면 추천 받은 시각이 더 이를때만
			min = i; //교체			
		
			
		
	}

	//추천수 제일적고 오래된사람 한명 제외시키기
	recommend[min] = 0; 
	rtime[min] = 0;
			

	//이번에 추천받은 사람 추가하기
	recommend[id] = 1;
	rtime[id] = t;
			
}
```

2021-12-07 06:17 UTC, flowersayo commented on 11월 30일- 최소신장트리/1774.cpp
> +    }
방금 튜터님들께서 작성해주신 모범풀이(?) 보고 왔는데 이미 연결된 정점은 유니온 연산해서 같은 집합에 속해있게 하는거더라구요! 많이 배워갑니다 👍

2021-12-07 06:29 UTC, flowersayo commented on 11월 30일- 최소신장트리/21924.cpp
> +int main() {
2번이었네요............ㅎㅎ핳ㅎ  최대 비용의 범위가 가중치( 10^6 )* 도로의개수( 10^5) 이므로 long long 자료형을 써야 할 것 같아요 감사합니다 !!!!🤩

2021-12-07 07:27 UTC, flowersayo commented
16232번 추가제출합니다! (같은 브랜치에 해서 죄송해요 😢😢)

2021-12-07 10:24 UTC, HyunJiLim0406 reviewed
p3
수고하셨습니다! 진짜 잘 수정해주셨어요. 추가제출분은 다른 튜터님이 확인해주실거예요! 이전에 풀어주신 부분에 대해선 더 드릴 조언이 없네요!

2022-01-04 01:48 UTC, merged