[우선순위 큐] 9월 20일
Altu-Bitu/Altu-Bitu_seoyeon pull request #4
Opened 2021-09-19 21:03 UTC by flowersayo

필수 2문제 + 선택 3문제 (11723,12018,15903) 풀었습니다! 

그리고 저번 스택,큐,덱에서 못푼 몇푼제를 해결했는데 머지하고 싶어서 올렸습니다(+예제푼것까지) ! 참고해주세요 :)

2021-09-20 05:59 UTC, HyunJiLim0406 requested changes
p1
수고하셨습니다! 지난 문제들도 그냥 소소하게 코멘트 달았어요~
함수화도 잘해주셨고, 리팩토링을 고민하신 흔적이 보이네요!
근데 저희가 생각했던 풀이와 다른 풀이가 조금 있어서 p1입니다! 저희가 다양한 풀이를 고려하고 미리 안내를 해드렸어야 했는데, 미처 생각하지 못했어요...ㅠ

수정 후 리뷰어로 저 호출해주세요!
추석 잘 보내세요 서연님~!

2021-09-20 05:59 UTC, HyunJiLim0406 commented on 9월 10일- 스택,큐,덱/10828.cpp
> +    //어짜피 다음번 push할때 그 인덱스가 사용자가 입력한 값으로 바꿔치기 되기 때문.
제가 언급하지 않았던 부분같은데 잘 캐치하셨네요!

2021-09-20 05:59 UTC, HyunJiLim0406 commented on 9월 10일- 스택,큐,덱/5430.cpp
> +}
오 이걸 직접 구현하셨네요! c++이 파싱이 까다롭다는 단점이 있긴해요

2021-09-20 05:59 UTC, HyunJiLim0406 commented on 9월 10일- 스택,큐,덱/5430.cpp
> +}
이게 동작하지 않나요? 문제가 있어보이진 않는데요!
그나저나 이 함수에서 하는걸 toggle이라고도 불러요! true->false / false->true로 상태가 toggle 되니까요!
그래서 이건 굳이 함수로 하지 않아도 한 줄로 처리할 수 있어요!

2021-09-20 05:59 UTC, HyunJiLim0406 commented on 9월 10일- 스택,큐,덱/5430.cpp
> +}
여기도 복잡한 부분은 아니라서 그냥 main에 넣고 isreverse 변수가 지역변수로 들어오는게 더 좋아요!
하핳 헷갈리져...뭐는 함수화가 좋다고 하고 뭐는 메인에 넣어도 된다고 하고...!
풀다보면 감이 올거예요

2021-09-20 05:59 UTC, HyunJiLim0406 commented on 9월 10일- 스택,큐,덱/5430.cpp
> +			continue; //에러가 발생했다면 아래 출력문은 시행 X
잘 끊었어요!

2021-09-20 05:59 UTC, HyunJiLim0406 commented on 9월 10일- 스택,큐,덱/5430.cpp
> +	}
여기를 string 반환 함수로 만들어도 좋을 것 같아요!

2021-09-20 05:59 UTC, HyunJiLim0406 commented on 9월 14일- 우선순위 큐/11279.cpp
> +// N번째를 넘어서는 큰 값이 되고 필요가 없다.
*N번째를 넘어서는 작은 값이 되고 필요가 없다(=지금까지 구해놓은 N번째 큰 수보다도 작은 수이기 때문에 고려할 필요가 없다)

2021-09-20 05:59 UTC, HyunJiLim0406 commented on 9월 14일- 우선순위 큐/11279.cpp
> +int main() {
핳 별건 아닌데 이건 2075번이네요! 11279를 공부하시다가 수정하셨던걸까요?

2021-09-20 05:59 UTC, HyunJiLim0406 commented on 9월 14일- 우선순위 큐/11286.cpp
> +	priority_queue <int, vector<int>> negative; //음수만 담을 최대힙 (음수는 클수록 절댓값이 작아진다)
p1
잘 풀어주셨지만 이건 그렇게 어려운 문제가 아니에요!
정렬을 할 때도 저희가 compare 함수를 정의해서 정렬조건을 정의할 수 있었어요.
우선순위 큐도 그렇답니다! 훨씬 간단하게 풀어볼까요?

2021-09-20 05:59 UTC, HyunJiLim0406 commented on 9월 14일- 우선순위 큐/11723.cpp
> +    // 그게 아니라 그냥 s에 들어있는 값만 allSet과 똑같이 대입해주는거임.
맞아요! 접근이라기보다는 복사?의 개념으로 이해하시면 될거예요

2021-09-20 05:59 UTC, HyunJiLim0406 commented on 9월 14일- 우선순위 큐/11723.cpp
> +int main() {
p1
이 문제는 set으로 풀 수 있기도 한데요..!
사실 이건 저희가 원했던 풀이는 아닙니다~
수의 범위가 1~20으로 아주 작아요. 이 모든 연산을 각각 O(1)에 해결할 수 있을 것 같아요. 힌트 보고 다시 풀어볼까요?

2021-09-20 05:59 UTC, HyunJiLim0406 commented on 9월 14일- 우선순위 큐/12018.cpp
> +			//n개의 숫자를 입력받고 n번째 숫자를 찾을때에는 우선순위큐 쓰는게 더 효율적인가요?
오 잘 분석해주셨네요!
이 정도의 효율성 차이면 그냥 취향에 맞는걸 쓰시는게 좋아요!
저라면...벡터를 쓰겠습니다! 왜냐면 우선순위큐를 사용하면 n번째로 마일리지를 많이 넣은 사람을 찾을 때까지 pop을 해야하니까요! 코드도 좀 길어지고 해서 전 그냥 v[limit-1]를 리턴받겠습니다~
각 컨테이너가 차지하는 메모리도 고려 대상에 들어갈 순 있지만 그렇게 큰 영향은 없을거예요!

2021-09-20 05:59 UTC, HyunJiLim0406 commented on 9월 14일- 우선순위 큐/12018.cpp
> +		if (m_my >= k) //보유 마일리지가 그 과목이 요구하는  마일리지보다 크다면
이 조건까지 while문에 넣으면 else-break 부분이 필요없어지겠네요!

2021-09-20 05:59 UTC, HyunJiLim0406 commented on 9월 14일- 우선순위 큐/15903.cpp
> +
출력값이 어떻게 나왔나요? 전 2,147,483,648,000,000이 나오네요!

2021-09-20 05:59 UTC, HyunJiLim0406 commented on 9월 14일- 우선순위 큐/3613.cpp
> +	return true;
이건 한줄로 처리할 수 있겠네요!

2021-09-20 05:59 UTC, HyunJiLim0406 commented on 9월 14일- 우선순위 큐/3613.cpp
> +
👍

2021-09-20 05:59 UTC, HyunJiLim0406 commented on 9월 14일- 우선순위 큐/3613.cpp
> +
상수 처리 좋네요!

2021-09-20 05:59 UTC, HyunJiLim0406 commented on 9월 14일- 우선순위 큐/3613.cpp
> +int main() {
저희 함수는 어떻게 표기하기로 약속했었나요!

2021-09-22 09:06 UTC, flowersayo commented on 9월 10일- 스택,큐,덱/5430.cpp
> +}
아하 그렇네요 지금상태랑 반대로한다면 한줄이면 충분하겠네요..ㅎ핳
```case  'R':
	isreverse=!reverse; //지금상태와 반대로.
		break;```
이렇게 고쳤습니다!

2021-09-22 09:14 UTC, flowersayo commented on 9월 10일- 스택,큐,덱/5430.cpp
> +}
튜터님 말씀 무슨소린지 알것같아요! 함수를 구현하는목적은 코드를 간소화 + 가독성있게 하기 위해선데 함수로 너무 사소한 기능을 구현하게 되면  오히려 코드가 더 길어지고 메인에 두면 한번에 볼 수 있는걸 오히려 가독성도 더 떨어지게(?) 할 수 있는 것 같아요 좋은 조언 감사합니다!!!!

2021-09-22 09:39 UTC, flowersayo commented on 9월 10일- 스택,큐,덱/5430.cpp
> +	}
넵넵~! 아래와 같이 바꿨습니다!

```
string dqToString(deque<int> dq)   // 상태에 따라 덱에 들어있는 숫자를 스트링으로 반환하는 함수
{
	string s = "";

	s += '[';

	if (!isreverse) //정상상태라면
	{
		while (dq.size())
		{

			s += to_string (dq.front()); //숫자를 문자로
			dq.pop_front();

			if (!dq.empty())
				s += ',';

		}
	}

	else //뒤집힌 상태라면
	{

		while (dq.size())
		{

			s += to_string( dq.back());
			dq.pop_back();

			if (!dq.empty())
				s += ',';

		}
	}

	s += ']';

	return s;


}```

2021-09-22 09:47 UTC, flowersayo commented on 9월 14일- 우선순위 큐/11279.cpp
> +int main() {
엇 ...그러게요 몰랐네요 ! 번호 수정했습니다 핳... 😂

2021-09-22 10:13 UTC, flowersayo commented on 9월 14일- 우선순위 큐/11286.cpp
> +	priority_queue <int, vector<int>> negative; //음수만 담을 최대힙 (음수는 클수록 절댓값이 작아진다)
애초에 우선순위큐에 넣을때부터 cmp함수 통해  1. 절댓값 작은순 2. 절댓값 같다면 더 작은순으로 정렬하는 방법으로 수정했습니다!  제가 하드코딩 했었네요 핳ㅎ

 ```struct cmp {
	bool operator()(int a, int b) {

		if (abs(a) == abs(b)) //절댓값이 같다면
			return a > b; //크기가 작은순서대로 (sort함수와 반대)

		return abs(a) > abs(b);//절댓값이 작은 순서대로

	}
	
};```

근데 공식 풀이보고 궁금한점이 생겼습니다. (정말 기본적인것일지도.. ) 일반 벡터의 정렬과 다르게 우선순위큐의 cmp 를 만들때에는 struct cmp 라는 구문이 추가되는데 이것의 정체(?)가 무엇인지 궁금합니다. cmp는 '함수' 여야하는걸로 알고 있는데 갑자기 구조체가 뜬금없이 등장하는 이유가 무엇인지 ..😂

2021-09-22 10:28 UTC, flowersayo commented on 9월 14일- 우선순위 큐/11723.cpp
> +int main() {
힌트보고 bool 배열활용해서 재풀이했습니다! 이런 효과적이고 좋은 방법이 있었네요 ...😂

2021-09-22 10:30 UTC, flowersayo commented on 9월 14일- 우선순위 큐/3613.cpp
> +	return true;
그렇네요!!!!
```
bool is_java(string str) { 	//str은 _가 없는 상태

	return !isupper(str[0]);

}
```

2021-09-22 10:40 UTC, flowersayo commented on 9월 14일- 우선순위 큐/3613.cpp
> +int main() {
카멜 표기법으로 바꿨습니다 ! !

2021-09-22 10:42 UTC, flowersayo commented
추석세고 오느라 피드백반영이 많이 늦었네요 ㅠㅠㅠㅠ 현지님도 추석 잘 보내셨을지 모르겠어요 핳ㅎㅎㅎ... 
우선 좋은 피드백 남겨주셔서 감사합니다! 피드백 주신것들 다 반영했고  백준에서 잘 돌아가는지도 일일히 다 확인했어용 😁

2021-09-22 14:01 UTC, HyunJiLim0406 commented on 9월 14일- 우선순위 큐/11286.cpp
> +	priority_queue <int, vector<int>> negative; //음수만 담을 최대힙 (음수는 클수록 절댓값이 작아진다)
오호 이걸 어떻게 설명해드리면 좋을까요
음 일단 sort는 '함수'예요. 그리고 우선순위 큐는 '정의'하는거구요.
직접 다루진 않았지만 맵과 셋에서도 key의 정렬 기준을 설정할 수 있어요! 그때도 우선순위 큐처럼 구조체를 사용하구요.

`priority_queue<int, vector<int>, greater<>> min_heap`을 볼게요!
이걸 풀어서 설명하면 '어떤 우선순위 큐를 선언할 건데, 이 우선순위 큐는 int 자료형에 정렬 기준은 greater<>인 '구조체'야'라는 뜻이에요! [링크](https://kbj96.tistory.com/15) 이건 구글링하다가 발견한 블로그인데요. 소제목 4에서 Student 구조체 봐주세요! 구조체의 필드에 추가로 operator 함수가 정의되어 있네요! 그리고 우선순위 큐 선언시에는 복잡한것 없이 Student만 들어가 있구요. 여기서 좀 더 설명하면 c++의 객체지향적인 면을 설명해야만 하는데 알고리즘을 푸는 입장에서 거기까지 알 필요는 없어요!
그래서 그냥 우선순위 큐를 정의할 때 넘기는 인자들이 알고보니 다 구조체의 일부였구나..! 정도로만 생각하시면 될 것 같아요!

2021-09-22 14:05 UTC, HyunJiLim0406 reviewed
p3
수고하셨습니다~!
핳 저는 추석 그냥 평소와 같이 보냈네요~ 
이제 머지하셔도 됩니다!!

아 코드에도 적어놨지만 11723번에서 비트마스킹 풀이도 엄청 중요해요! 조금 어렵긴 하지만 샘플코드 한 번 봐주시면 좋아요~!

2021-09-22 14:05 UTC, HyunJiLim0406 commented on 9월 14일- 우선순위 큐/11723.cpp
> +		}
문제는 없지만 여기서 continue로 끊어가지 않으면 if문을 하나하나 다 확인하게 돼서 continue를 써주는게 좋아요

2021-09-22 14:05 UTC, HyunJiLim0406 commented on 9월 14일- 우선순위 큐/11723.cpp
> +
샘플 코드에서 비트마스킹 풀이도 봐주세요! 아주 중요합니다!!

2021-09-22 14:31 UTC, merged