[백트래킹] 9월 24일
Altu-Bitu/Altu-Bitu_seoyeon pull request #7
Opened 2021-09-30 02:56 UTC by flowersayo

1759,15665,10971 풀었습니다!  
1759,15665번은 맞았습니다! 그러나 10971번은 코드를 짜고 'o'를 출력하면서 확인해보니까 함수가 한번실행되고 말고, 재귀문(46번째줄)이 시행되지 않아 더 깊게 못들어가는거같아요 ..😂 제가 의심가는 부분은 continue문(36번째) 인데 원래 저의 의도는 연결이 끊어진 도시 탐색을 방지하고자 함이었거든요.. 근데 제 의도대로 동작하지 않는 것 같네요ㅠㅠ  사실 저부분만 문제가 있는건 아닌거같아서 핳... 전체적으로 어디를 고쳐야할지 피드백 받을 수 있을까요..!

2021-09-30 05:17 UTC, HyunJiLim0406 requested changes
p2
수고하셨습니다! 백트래킹을 잘 이해하신 것 같아요!
외판원 순회가 틀린 이유는 코드에 적어놓았습니다
디버깅 시도 좋았어요! 아마 line 23에서 current를 출력하거나, line 42에서 i를 출력해봤으면 더 좋았을거예요~
수정 후 리뷰어로 저 호출해주세요

2021-09-30 05:17 UTC, HyunJiLim0406 commented on 9월 24일- 백트래킹/10971.cpp
> +
이건 약간 암묵적인 약속(?) 같은 건데요! 순회한 정점의 개수를 세는 cnt와 같은 변수는 보통 0부터 시작해서 증가하는게 좋아요!

2021-09-30 05:17 UTC, HyunJiLim0406 commented on 9월 24일- 백트래킹/10971.cpp
> +int main() {
오 일단 아주 백트래킹 자체로는 잘 작성하셨어요. 어디가 문제인지 알려면 재귀함수의 특징을 알아야해요!
저희가 재귀함수를 작성할 때는 무한루프에 빠지지 않도록 기저조건을 잘 작성해야 한다고 했었어요.
물론 지금 기저조건도 약간 문제가 있는 부분이 있긴하지만 주된 문제는 아니에요!

간단하게 1, 2, 3, 4번 마을이 있다고 할게요. 그리고 아무 마을이나 2개 골라도 둘 사이에는 길이 있다고 할게요!
1번 마을에서 출발했고 지금 check의 상태는 {F, F, F, F} 일거예요
1번 마을에서 2번 마을로 이동했어요! 그럼 이제 {F, T, F, F}가 되겠네요~

2번 마을에서...1번 마을을 갈 수 있네요..? 왤까요?
일단 길이 있고, 1번 마을은 체크되지 않았기 때문이에요!
자 그럼 다시 1번 마을에 왔고 이제 {T, T, F, F}가 되겠네요. 뭔가 꼬이고 있는것 같지 않나요 하핳

모든 마을 사이에 길이 있다고 했으니까 아마 외판원은...
1->2->1->3->4->1 이렇게 순회하지 않았을까요?

어디가 문제인지 눈치 채셨을까요?
그리고 기저조건에도 사소한 문제가 하나 있어요!
지금은 모든 도시를 돌았고, 시작점으로 되돌아가는 길이 있을 때만 조건문에 걸려서 리턴이 돼요
그럼 모든 도시를 돌았지만, 시작점으로 되돌아가는 길이 없다면 어떻게 되나요?

2021-09-30 05:17 UTC, HyunJiLim0406 commented on 9월 24일- 백트래킹/15665.cpp
> +    num.erase(unique(num.begin(), num.end()), num.end()); //중복원소를 vector의 제일 뒷부분으로 보낸다음 쓰레기 값 삭제.
p2
이걸 한번에 하는 방법이 뭐였었나요!

2021-09-30 05:17 UTC, HyunJiLim0406 commented on 9월 24일- 백트래킹/1759.cpp
> +		}
여기는 비밀번호의 유망성을 체크하는 부분이니까 promising 함수로 만드는게 좋아요
그나저나 알파벳은 26개밖에 안되니까 그 중에 모음이 뭔지 미리 체크해두면 line 29가 간단해질 것 같네요!

2021-10-01 02:53 UTC, flowersayo commented on 9월 24일- 백트래킹/10971.cpp
> +int main() {
헐.. 현지님이 설명을 너무 쉽게 잘해주셔서  이해가 한번에 됐어요!! 다시 시작지로 돌아가는 불상사가 생긴다는 것이죠? 근데 제가 말씀주신 부분에 대해서 생각해보았는데 물론 1 -> 2 -> 1 과 같이 시작점을 도로 방문하는 일이 생기긴 하지만,  결국 if문에 걸리지 않고 무사히 리턴되니까 결과에 미치는 영향은 없을 것이라고 생각해서 그렇게 코드를 짠거였어요.. ! 물론 조금 비효율적이긴 하지만 아무리생각해도 시작지점을  다시방문하지 못하게하면 start =current인 경우가 생기지 않아서 더 문제가 심각해지더라구요..😂   


![KakaoTalk_20211001_114246239](https://user-images.githubusercontent.com/86418674/135557537-95853a46-0e48-4c0e-9265-2fb2e1475f98.jpg)

정리하자면,  모든 도시를 돌았을때 시작점으로 되돌아가는 길이 없는 상황은  ( cnt =n 이고 start!=current 인 경우)은 마지막이 아닌 중간에 시작지점으로 돌아갔다는 것이고, 이는 마지막 기저조건을 만족하지 못하고 모든지점을 방문하여 check배열이 모두 false인 상태 {F,F,F,F}이므로 더 이상 재귀 호출이 일어나지도 않는 상황이 되어 그냥 리턴한다. 와 같이 생각했는데 혹시 틀린점이 있을까요? 그림은 제가 짠 코드 그림으로 정리해본건데 혹시 도움이 될까 싶어서 같이 올려요!! 

그래서 결론은, 시작지를 다시 방문하는 일이 생기긴하지만 정답에 미치는 영향은 없으니 괜찮지 않나요?!! 하는 질문이에요!

2021-10-01 02:56 UTC, flowersayo commented on 9월 24일- 백트래킹/15665.cpp
> +    num.erase(unique(num.begin(), num.end()), num.end()); //중복원소를 vector의 제일 뒷부분으로 보낸다음 쓰레기 값 삭제.
저도 set을 이용하고 싶었는데 set에는 랜덤한 인덱스에 접근하는 기능이 없어서 어떻게 활용해야할지 조금 난감하더라구요 핳ㅎ ㅠㅠㅠㅠ 그래서 벡터를 이용했었는데 지금 set을 이용해서도 한번 풀어볼게요!

2021-10-01 02:59 UTC, flowersayo commented on 9월 24일- 백트래킹/10971.cpp
> +
헐 진짜 충격적이에요... 왜 i로 안썼을까요 하하..ㅎㅎㅎ ㅠ

2021-10-01 03:01 UTC, flowersayo commented on 9월 24일- 백트래킹/10971.cpp
> +int main() {
+ 더 보태면 cnt =n이 되는 호출에는 (모든 도시를 다 도는 순간) 어짜피 bool배열이 모두 f일테니  더 깊게 들어가지 않는다...? 와 비슷한 맥락이에요!

2021-10-01 03:08 UTC, HyunJiLim0406 commented on 9월 24일- 백트래킹/10971.cpp
> +int main() {
서연님이 생각하신 것도 맞아요!
어차피 기저조건에 걸리지 않아도 check 배열이 다 false라 알아서 리턴될거고 중간에 시작점을 방문해도 가지치기에서 걸러질거예요

근데 코드는 항상 다른 사람이 볼 수 있다는걸 염두하고 작성해야해요!
이 문제의 기저조건이 정말 `cnt =n && start==current`가 맞을까요?
사실 정확한 기저조건은 `cnt=n`이에요! 그럼 `start==current`는 뭘까요?
이건  최소비용을 갱신할 조건문이라고 할 수 있어요. 최후의 가지치기?같은거라고 생각하시면 돼요.

조금 헷갈리실 수도 있는데 저희가 샘플코드로 이 문제의 순열버전을 준비했어요! 그거랑 같이 보면 좋을 것 같아요
도시의 순서를 정해서 n개를 고르는건 항상 할 수 있는 일이에요! 근데 그 선택 중 마지막 지점에서 다시 시작 지점으로 돌아오는 경우는 일부예요!

그래서 기저조건은 일반적인 경우에 항상 성립하는 조건으로 선택해야해요! 그렇기 때문에 일반적으로 원소를 고르는 대부분의 백트래킹 문제의 기저조건은 n개의 원소를 골랐을 때예요!

FFFF로 리턴이 되긴하지만, 어쨌든 기저조건에 걸리지 않아 아래로 내려갔다는건 도시 n개를 돌았음에도 또 다른 도시를 탐색해야 한다는 의미로 해석될 수 있어요! 그럼 저희 문제의 의도와 많이 달라지겠네요!

이와 마찬가지로 이 문제에선 적용이 안되겠지만, 극단적으로 1-2번 도시 사이의 거리가 -1이라고 할게요! 물리적으로 불가능하지만, 두 정점 사이의 거리가 음수인 관계를 중간고사 이후에 배울거예요! 그렇다면 1->2->1->3->...의 거리가 정상적으로 순회한 경로보다 비용이 적게 들겠네요! 그럼 이게 최소비용이 되는거예요. 이게 불가능한 문제는 아니기 때문에 문제의 의도와 맞지 않게 시작점을 재방문하는건 위험합니다!

그럼 시작점을 방문처리하면 다시 시작점으로 돌아갈 수 없는 문제는 어떻게 해결할까요?
그건 서연님이 작성해주신 메인에 답이 있어요! 우린 이미 이번 순회의 시작점이 어디인지 알고있어요!
그렇다면, 마지막 도시까지 다녀온 후, 그 도시와 시작점 사이에 길이 있는지 확인하면 되겠네요!

사실 이 문제에서 도시를 순회하는 방법은 시작점으로 돌아오기 때문에 원 형태예요!
앞으로 이런 원 형태의 문제를 종종 접하게 될텐데, 이런 문제를 풀 때의 팁은 시작점을 고정하는거예요
그럼 원형태가 아니라 선형태로 바뀌거든요!

그래서 결론은 이 문제에선 그렇게 코드를 작성해도 문제가 없지만 논리적으로 맞지 않기 때문에 수정해야 한다는 것입니다!! 이해가 안되는 부분이 있으시다면 알려주세요~!

2021-10-01 03:10 UTC, HyunJiLim0406 commented on 9월 24일- 백트래킹/15665.cpp
> +    num.erase(unique(num.begin(), num.end()), num.end()); //중복원소를 vector의 제일 뒷부분으로 보낸다음 쓰레기 값 삭제.
랜덤 인덱스를 접근하지 않으셔도 괜찮아요!
아니면 셋에 넣었다가 벡터애 한 번에 옮겨도 좋구요~

2021-10-01 04:21 UTC, flowersayo commented on 9월 24일- 백트래킹/10971.cpp
> +int main() {
아아아 진짜 너무 이해가 잘됐어요 ㅠㅠㅠ 어쩜 이렇게 설명을 명확하게 잘 해주시는지 .. 그리고 바쁘실텐데 이렇게 장문으로 답장해주셔서 점말 감동입니다 ❤

정리하자면, 기저조건은 모든 노드들이 리턴할 수 있게끔 하는 일반적인 경우로 만들어야한다. 그렇지 않으면 기저조건에 걸리지 않아 아래로 내려가는 경우가 생겨 이는 위험하고 (무한루프) 논리적이지 못하다. 또한 본 문제는 마지막 -> 시작점으로 연결되므로 원 형태이다. 그리고 n개에서 원순열을 만드는 방법의 가짓수는 총 (n-1)! 인데 우리는 n개의 숫자중 시작점 제외 n-1개를 먼저 뽑은다음 ex) 시작지: 0 일경우 나머지 원소를 순열로 뽑는다. 1,2,3 / 1,3,2 / 2,1,3 / 2,3,1 /3,1,2/3,2,1 그리고 이경우에 한해서만 마지막 방문한 장소 -> 시작지 를 연결하는 경로가 있는지 확인해주고 최소비용을 갱신한다. 이렇게하면 문제가 원형태가 아니라 선 형태로 바뀐다. 라고 이해했어요!

2021-10-01 04:28 UTC, flowersayo commented on 9월 24일- 백트래킹/1759.cpp
> +		}
모든 피드백 반영해서 방금 푸쉬해두었습니다! 머지해도 될까요?

2021-10-01 04:28 UTC, flowersayo commented
모든 피드백 반영해서 방금 푸쉬해두었습니다! 머지해도 될까요?

2021-10-01 04:37 UTC, HyunJiLim0406 commented on 9월 24일- 백트래킹/10971.cpp
> +int main() {
맞아요!
제가 이런류의 문제를 설명할 때 하는 얘기가 원순열인데 딱 캐치해주셨네요!
이번에 동적계획법 과제 중에 RGB 거리를 성공하신다면 바로 다음 RGB 거리2를 시도해보셔도 좋을 것 같아요

2021-10-01 04:37 UTC, HyunJiLim0406 reviewed
p3
수고하셨습니다! 머지해주세요~

2021-10-01 04:53 UTC, merged